// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHM9NW_Pus-Y_TgC5vJ24ghRsC8aM7raM',
    appId: '1:363301007083:web:7c94814d6c586b3afd58ae',
    messagingSenderId: '363301007083',
    projectId: 'fir-f8760',
    authDomain: 'fir-f8760.firebaseapp.com',
    storageBucket: 'fir-f8760.appspot.com',
    measurementId: 'G-GXHTSQ9L1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJYffvrVPrJBHVYim5ULIrxnzGLTNfCPI',
    appId: '1:363301007083:android:4475e41198dda56dfd58ae',
    messagingSenderId: '363301007083',
    projectId: 'fir-f8760',
    storageBucket: 'fir-f8760.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMGoq010ytUC-84xFfd_oR6-r5lhaR0DI',
    appId: '1:363301007083:ios:11fae2018f726fa4fd58ae',
    messagingSenderId: '363301007083',
    projectId: 'fir-f8760',
    storageBucket: 'fir-f8760.appspot.com',
    iosBundleId: 'com.example.loginIgnup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMGoq010ytUC-84xFfd_oR6-r5lhaR0DI',
    appId: '1:363301007083:ios:18b24ce77ce57358fd58ae',
    messagingSenderId: '363301007083',
    projectId: 'fir-f8760',
    storageBucket: 'fir-f8760.appspot.com',
    iosBundleId: 'com.example.loginIgnup.RunnerTests',
  );
}
